<a href="https://colab.research.google.com/github/harshulgupt/Machine-Learning/blob/master/Python_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy


In [0]:
import numpy as np


In [0]:
a=np.array([2,7,1,99,4])

In [0]:
type(a)


numpy.ndarray

In [0]:
b=np.array([21,17,11,199,14])

In [0]:
a


array([ 2,  7,  1, 99,  4])

In [0]:
b


array([ 21,  17,  11, 199,  14])

In [0]:
a[1]


7

In [0]:
a+b


array([ 23,  24,  12, 298,  18])

In [0]:
a**2


array([   4,   49,    1, 9801,   16])

In [0]:
a**3


array([     8,    343,      1, 970299,     64])

In [0]:
vim mathops.py


SyntaxError: ignored

In [0]:
c=np.array([1.2])

In [0]:
a+c


array([  3.2,   8.2,   2.2, 100.2,   5.2])

In [0]:
c=np.array([1,2])

In [0]:
a+c


ValueError: ignored

In [0]:
d+np.array([[1,2,3],[4,5,6],[7,8,9]])

NameError: ignored

In [0]:
d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [0]:
d


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
x=np.array([[2,5,8],[3,6,1],[7,8,9]])

In [0]:
x


array([[2, 5, 8],
       [3, 6, 1],
       [7, 8, 9]])

In [0]:
x=np.array([[2,5,8],[3,6,1]
            )

SyntaxError: ignored

In [0]:
x=np.array([[2,5,8],[3,6,1])
            
            

SyntaxError: ignored

In [0]:
x=np.array([[2,5,8],[3,6,1]])

In [0]:
x


array([[2, 5, 8],
       [3, 6, 1]])

In [0]:
x[0]


array([2, 5, 8])

In [0]:
x[0][1]


5

In [0]:
x+1


array([[3, 6, 9],
       [4, 7, 2]])

In [0]:
x+7

array([[ 9, 12, 15],
       [10, 13,  8]])

In [0]:
x**2


array([[ 4, 25, 64],
       [ 9, 36,  1]])

In [0]:
z=np.array([[2,7],[3,8],[2,9],[9.4]])

In [0]:
z

array([list([2, 7]), list([3, 8]), list([2, 9]), list([9.4])],
      dtype=object)

In [0]:
z=np.array([[2,7],[3,8],[2,9],[9,4]])

In [0]:
z


array([[2, 7],
       [3, 8],
       [2, 9],
       [9, 4]])

In [0]:
z.shape

(4, 2)

In [0]:
z[0:2]

array([[2, 7],
       [3, 8]])

In [0]:
z[0:
 ]

array([[2, 7],
       [3, 8],
       [2, 9],
       [9, 4]])

In [0]:
z[0:,
 ]

array([[2, 7],
       [3, 8],
       [2, 9],
       [9, 4]])

In [0]:
z[0:,0
 ]

array([2, 3, 2, 9])

In [0]:
z[1:,0
 ]

array([3, 2, 9])

In [0]:
x[0:,1]

array([5, 6])

In [0]:
x[0:,[0,2]]

array([[2, 8],
       [3, 1]])

In [0]:
z[[0,3],1]

array([7, 4])

In [0]:
b=numpy.array([1,9,7],[3,2,8],[4,5,6],[2,9,0])

ValueError: ignored

In [0]:
b=np.array([1,9,7],[3,2,8],[4,5,6],[2,9,0])

ValueError: ignored

In [0]:
b=np.array([[1,9,7],[3,2,8],[4,5,6],[2,9,0]])

In [0]:
b


array([[1, 9, 7],
       [3, 2, 8],
       [4, 5, 6],
       [2, 9, 0]])

In [0]:
b[1:3,1]

array([2, 5])

In [0]:
x


array([[2, 5, 8],
       [3, 6, 1]])

In [0]:
x.reshape(3,2)

array([[2, 5],
       [8, 3],
       [6, 1]])

In [0]:
dir(np)


['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '_distributor_init',


In [0]:
for i in dir(np)
  if 'zer' in i:
    print(i)
    

SyntaxError: ignored

In [0]:
for i in dir(np)
  if 'zer' in i:
    print(i):
    

SyntaxError: ignored

In [0]:
for i in dir(np):
  if 'zer' in i:
    print(i)
    

count_nonzero
flatnonzero
nonzero
trim_zeros
zeros
zeros_like
